# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Test_ask.fm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test_ask.fm

  target 'Test_ask.fmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test_ask.fmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
